from __future__ import annotations


def synthetic_project() -> dict:
    weekdays = ["MON", "TUE", "WED", "THU", "FRI"]
    shifts = []
    for day in weekdays:
        shifts.extend(
            [
                {
                    "calendar_id": "DEMO_CALENDAR",
                    "weekday": day,
                    "shift_name": "Shift A",
                    "start_time": "08:00",
                    "end_time": "12:00",
                    "enabled": True,
                },
                {
                    "calendar_id": "DEMO_CALENDAR",
                    "weekday": day,
                    "shift_name": "Shift B",
                    "start_time": "12:00",
                    "end_time": "16:00",
                    "enabled": True,
                },
            ]
        )
    return {
        "metadata": {
            "project_id": "SYNTHETIC_DEMO",
            "project_name": "Synthetic industrial installation",
            "revision_id": "DEMO_001",
            "project_start": "2030-01-07T00:00:00+00:00",
            "active_calendar": "DEMO_CALENDAR",
            "notes": "Neutral data created solely for automated testing.",
        },
        "systems": [
            {
                "system_id": "EARLY_ENABLERS",
                "name": "Early enablers",
                "family": "Site preparation",
                "arrival_date": "2030-01-07T00:00:00+00:00",
                "delivery_state": "Not applicable",
                "assembly_location": "Demo facility",
                "installation_zone": "SERVICE_AREA",
                "template_version": "DEMO_V1",
                "enabled": True,
                "notes": "Independent preparation before equipment arrival.",
            },
            {
                "system_id": "EQUIPMENT_SKID",
                "name": "Equipment skid",
                "family": "Packaged equipment",
                "arrival_date": "2030-01-09T08:00:00+00:00",
                "delivery_state": "Factory assembled",
                "assembly_location": "Demo facility",
                "installation_zone": "ASSEMBLY_AREA",
                "template_version": "DEMO_V1",
                "enabled": True,
                "notes": "Synthetic equipment with acceptance before availability.",
            },
        ],
        "packages": [
            {
                "package_id": "SITE_PREPARATION",
                "system_id": "EARLY_ENABLERS",
                "name": "Site preparation",
                "template": "DEMO_SITE_PREP",
                "enabled": True,
                "display_order": 1,
            },
            {
                "package_id": "SKID_ACCEPTANCE",
                "system_id": "EQUIPMENT_SKID",
                "name": "Receipt and acceptance",
                "template": "DEMO_ACCEPTANCE",
                "enabled": True,
                "display_order": 1,
            },
            {
                "package_id": "SKID_INSTALLATION",
                "system_id": "EQUIPMENT_SKID",
                "name": "Installation",
                "template": "DEMO_INSTALLATION",
                "enabled": True,
                "display_order": 2,
            },
        ],
        "activities": [
            {
                "activity_id": "PREPARE_FOUNDATION",
                "package_id": "SITE_PREPARATION",
                "name": "Prepare foundation",
                "duration_h": 8,
                "duration_basis": "WORK_TIME",
                "preemptible": False,
                "calendar_id": "DEMO_CALENDAR",
                "requires_system_arrival": False,
                "enabled": True,
                "template_origin": "DEMO_SITE_PREP",
                "is_override": False,
                "notes": "Uses the same crew as service routing.",
            },
            {
                "activity_id": "ROUTE_SERVICES",
                "package_id": "SITE_PREPARATION",
                "name": "Route services to installation boundary",
                "duration_h": 10,
                "duration_basis": "WORK_TIME",
                "preemptible": True,
                "calendar_id": "DEMO_CALENDAR",
                "requires_system_arrival": False,
                "enabled": True,
                "template_origin": "DEMO_SITE_PREP",
                "is_override": False,
                "notes": "May pause at calendar gaps.",
            },
            {
                "activity_id": "ACCEPT_SKID",
                "package_id": "SKID_ACCEPTANCE",
                "name": "Inspect and accept delivered skid",
                "duration_h": 4,
                "duration_basis": "WORK_TIME",
                "preemptible": False,
                "calendar_id": "DEMO_CALENDAR",
                "requires_system_arrival": True,
                "enabled": True,
                "template_origin": "DEMO_ACCEPTANCE",
                "is_override": False,
                "notes": "The skid becomes available only after this activity.",
            },
            {
                "activity_id": "POSITION_SKID",
                "package_id": "SKID_INSTALLATION",
                "name": "Position equipment skid",
                "duration_h": 8,
                "duration_basis": "WORK_TIME",
                "preemptible": False,
                "calendar_id": "DEMO_CALENDAR",
                "requires_system_arrival": True,
                "enabled": True,
                "template_origin": "DEMO_INSTALLATION",
                "is_override": False,
                "notes": "Continuous across adjacent crew shifts.",
            },
            {
                "activity_id": "FINAL_CONNECTION",
                "package_id": "SKID_INSTALLATION",
                "name": "Complete final service connection",
                "duration_h": 4,
                "duration_basis": "WORK_TIME",
                "preemptible": False,
                "calendar_id": "DEMO_CALENDAR",
                "requires_system_arrival": True,
                "enabled": True,
                "template_origin": "DEMO_INSTALLATION",
                "is_override": False,
                "notes": "Requires both prior routing and final positioning.",
            },
            {
                "activity_id": "SEAL_CURE",
                "package_id": "SKID_INSTALLATION",
                "name": "Allow connection seal to cure",
                "duration_h": 24,
                "duration_basis": "ELAPSED_TIME",
                "preemptible": False,
                "requires_system_arrival": True,
                "enabled": True,
                "template_origin": "DEMO_INSTALLATION",
                "is_override": False,
                "notes": "Elapsed time continues outside work shifts.",
            },
        ],
        "gates": [
            {
                "gate_id": "SKID_AVAILABLE",
                "system_id": "EQUIPMENT_SKID",
                "package_id": "SKID_ACCEPTANCE",
                "name": "Skid accepted and available",
                "gate_type": "AVAILABLE",
                "exposed": True,
                "is_project_milestone": False,
                "notes": "Generated by receipt and acceptance.",
            },
            {
                "gate_id": "SKID_POSITIONED",
                "system_id": "EQUIPMENT_SKID",
                "package_id": "SKID_INSTALLATION",
                "name": "Skid positioned",
                "gate_type": "READY",
                "exposed": True,
                "is_project_milestone": True,
                "notes": "Required before final service connection.",
            },
            {
                "gate_id": "PROJECT_COMPLETE",
                "name": "Synthetic project complete",
                "gate_type": "PROJECT_COMPLETE",
                "exposed": True,
                "is_project_milestone": True,
                "notes": "Final objective for the synthetic project.",
            },
        ],
        "dependencies": [
            {
                "dependency_id": "DEP_001",
                "source_type": "ACTIVITY",
                "source_id": "ACCEPT_SKID",
                "target_type": "GATE",
                "target_id": "SKID_AVAILABLE",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Acceptance creates availability.",
            },
            {
                "dependency_id": "DEP_002",
                "source_type": "GATE",
                "source_id": "SKID_AVAILABLE",
                "target_type": "ACTIVITY",
                "target_id": "POSITION_SKID",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Positioning requires accepted equipment.",
            },
            {
                "dependency_id": "DEP_003",
                "source_type": "ACTIVITY",
                "source_id": "PREPARE_FOUNDATION",
                "target_type": "ACTIVITY",
                "target_id": "POSITION_SKID",
                "relation": "FS",
                "lag_h": 2,
                "enabled": True,
                "rationale": "Foundation must be complete with elapsed settling lag.",
            },
            {
                "dependency_id": "DEP_004",
                "source_type": "ACTIVITY",
                "source_id": "POSITION_SKID",
                "target_type": "GATE",
                "target_id": "SKID_POSITIONED",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Positioning creates the state.",
            },
            {
                "dependency_id": "DEP_005",
                "source_type": "ACTIVITY",
                "source_id": "ROUTE_SERVICES",
                "target_type": "ACTIVITY",
                "target_id": "FINAL_CONNECTION",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Services can be routed early but must be ready before connection.",
            },
            {
                "dependency_id": "DEP_006",
                "source_type": "GATE",
                "source_id": "SKID_POSITIONED",
                "target_type": "ACTIVITY",
                "target_id": "FINAL_CONNECTION",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Final connection occurs only after positioning.",
            },
            {
                "dependency_id": "DEP_007",
                "source_type": "ACTIVITY",
                "source_id": "FINAL_CONNECTION",
                "target_type": "ACTIVITY",
                "target_id": "SEAL_CURE",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Cure starts after connection.",
            },
            {
                "dependency_id": "DEP_008",
                "source_type": "ACTIVITY",
                "source_id": "SEAL_CURE",
                "target_type": "GATE",
                "target_id": "PROJECT_COMPLETE",
                "relation": "FS",
                "lag_h": 0,
                "enabled": True,
                "rationale": "Cure completes the synthetic project.",
            },
        ],
        "resources": [
            {
                "resource_id": "INSTALL_CREW",
                "name": "Installation crew",
                "type": "HUMAN",
                "capacity": 1,
                "calendar_id": "DEMO_CALENDAR",
                "unlimited": False,
                "notes": "Shared by enabling and installation work.",
            },
            {
                "resource_id": "INSPECTION_CREW",
                "name": "Inspection crew",
                "type": "HUMAN",
                "capacity": 1,
                "calendar_id": "DEMO_CALENDAR",
                "unlimited": False,
                "notes": "Used for delivery acceptance.",
            },
        ],
        "activity_resources": [
            {"activity_id": "PREPARE_FOUNDATION", "resource_id": "INSTALL_CREW", "quantity": 1},
            {"activity_id": "ROUTE_SERVICES", "resource_id": "INSTALL_CREW", "quantity": 1},
            {"activity_id": "ACCEPT_SKID", "resource_id": "INSPECTION_CREW", "quantity": 1},
            {"activity_id": "POSITION_SKID", "resource_id": "INSTALL_CREW", "quantity": 1},
            {"activity_id": "FINAL_CONNECTION", "resource_id": "INSTALL_CREW", "quantity": 1},
        ],
        "resource_substitutions": [],
        "zones": [
            {
                "zone_id": "SERVICE_AREA",
                "name": "Service preparation area",
                "capacity": 2,
                "notes": "Allows limited concurrent work.",
            },
            {
                "zone_id": "ASSEMBLY_AREA",
                "name": "Assembly area",
                "capacity": 1,
                "notes": "Positioning requires exclusive occupancy.",
            },
        ],
        "activity_zones": [
            {"activity_id": "PREPARE_FOUNDATION", "zone_id": "ASSEMBLY_AREA", "load": 1, "exclusive": False},
            {"activity_id": "ROUTE_SERVICES", "zone_id": "SERVICE_AREA", "load": 1, "exclusive": False},
            {"activity_id": "POSITION_SKID", "zone_id": "ASSEMBLY_AREA", "load": "ALL", "exclusive": True},
            {"activity_id": "FINAL_CONNECTION", "zone_id": "ASSEMBLY_AREA", "load": "ALL", "exclusive": True},
            {"activity_id": "SEAL_CURE", "zone_id": "ASSEMBLY_AREA", "load": 1, "exclusive": False},
        ],
        "calendars": [
            {
                "calendar_id": "DEMO_CALENDAR",
                "name": "Synthetic weekday calendar",
                "timezone": "UTC",
                "valid_from": "2030-01-01",
                "valid_to": "2030-12-31",
                "weekend_days": ["SAT", "SUN"],
                "notes": "Two adjacent four-hour shifts form one eight-hour window.",
            }
        ],
        "calendar_shifts": shifts,
        "milestone_priorities": [
            {
                "gate_id": "PROJECT_COMPLETE",
                "priority": 1,
                "enabled": True,
                "notes": "Default makespan objective.",
            }
        ],
    }
